events {}

http {
  include /etc/nginx/mime.types;

  server {
    listen 80 default_server;
    server_name _;
    root /usr/share/nginx/html;

    location / {
      try_files $uri $uri/ /index.html;
    }
  }

  server {
    listen 80;
    server_name cashu-sync-wallet.fly.dev;
    return 301 https://silentlink.fly.dev$request_uri;
  }
}
